In [1]:
import pandas as pd
import numpy as np
import os
import glob
from pandas import DataFrame, read_csv
import matplotlib.pyplot as plt
import pandas as pd
import wfdb
import statsmodels.api as sm
import matplotlib.image as mpimg
import tkinter as tk

In [22]:
df = pd.read_csv('RecordsAnno4.csv',sep=',')
dfx = df[['RecordNum','PatientId','ICUStayId','Duration','Category']]
dfx.loc[:,'nRRraw'] = 0
dfx.loc[:,'nRRfilt'] = 0
dfx.loc[:,'nSpO2raw'] = 0
dfx.loc[:,'nSpO2filt'] = 0
dfx.loc[:,'nRD'] = 0
display(dfx)

,RecordNum,PatientId,ICUStayId,Duration,Category,nRRraw,nRRfilt,nSpO2raw,nSpO2filt,nRD
0,3887555,79,290076,38.200000,D,0,0,0,0,0
1,3647298,85,291697,45.316667,B,0,0,0,0,0
2,3485814,123,227264,34.000000,C,0,0,0,0,0
3,3991520,124,255660,53.016667,F,0,0,0,0,0
4,3807277,124,255660,32.316667,F,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
907,3912588,98481,290141,94.383333,X,0,0,0,0,0
908,3768185,98481,290141,47.600000,A,0,0,0,0,0
909,3391887,98481,290141,94.416667,A,0,0,0,0,0
910,3831114,99783,236983,68.566667,B,0,0,0,0,0
911,3286482,99783,236983,88.483333,B,0,0,0,0,0